### ISSUE TITLE
support `Chain.create` using a prompt and drop contract editor

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aerepl#17]
After `Chain.create` is introduced there is no need for a contract editor anymore. Users should be able to provide the sourcecode of a contract via prompt for `Chain.create` and the contract to be assigned to the defined variable.

- [ ] The user should be able to register contracts and contract interfaces in the prompt

**Comment by radrow** [comment]
In the new design we don't plan on doing it -- we are going to rely on importing contracts
